numerique-gouv/audioconf

controllers/createConfController.js, index.js, static/css/custom.css, views/confCreated.ejs, views/partials/footer.ejs
Give helpful hints to the user when they are stuck because the email didn't arrive.
- display which email address the email was sent to (so they can check for typos)
- add a contact button (also in footer)
- clean up the text.
=> Help user when email does not arrive

controllers/createConfController.js, index.js, static/css/custom.css, test/createConfControllerTest.js, urls.js, views/landing.ejs, views/legalNotice.ejs, views/partials/footer.ejs
Add legal notice page. 
Make url strings more easily modifiable by placing them all in an object.
Note : PR is in draft until the legal notice is filled in
Edit : filled in
=> Add legal notice

index.js, views/landing.ejs, views/partials/header.ejs
- Add descriptive titles for each page
- Fix header levels
- Fix an alt text
- Add an icon to signify error
=> Accessibility fixes

controllers/createConfController.js, lib/conferences.js, lib/emailer.js, lib/format.js, views/landing.ejs, views/partials/brand.ejs, views/partials/footer.ejs
Display freeAt date in email : 
Detail which emails are accepted, and what to do if not : 
New logo in header : 
New logo in footer
remove unused links (to be added back later with corresponding pages)
Add link to code repo
=> Petites ameliorations visuelles

lib/emailer.js, views/landing.ejs
+ correction du wording
Modification : 
- Email
- Landing page
=> Afficher le temps en heure (au lieu de minute)

views/partials/header.ejs
=> Ajout bouton darkmode

lib/emailer.js
=> Lien clickable dans l'email de validation

README.md, controllers/createConfController.js, docker-compose.yml, index.js, lib/db.js, lib/emailer.js, migrations/20201101122909_clean-conferences-table.js, static/css/custom.css, urls.js, views/confCreated.ejs, views/landing.ejs
=> Annulation de la conférence (Wait #18 before merge)

README.md, locust/docker-compose.yml, locust/locustfile.py
De ce que je comprends, après 1000 RPS, j'ai commencé à avoir des erreurs de connexion, je n'ai pas dépassé 1600 RPS (je suis peut être limité par mon ordinateur et ma connexion fibre).
Le formulaire de création de conf avec une faute de frappe plafonne à 40 RPS.
=> Test de charge LOCUST

lib/conferences.js
L'autre solution c'est de choisir l'email du rapport et si on change rien ça va sur infra@
=> Désactivation du rapport par email

index.js, lib/db.js, views/landing.ejs
@astranchet tu peux valider la forme, je merge en attendant
=> Afficher les numéros libres disponible

index.js, views/partials/header.ejs
When you do not specify a pageTitle, display the appName.
=> Default page titles

index.js, lib/format.js, views/confCreated.ejs
=> Display GMT timezone

views/legalNotice.ejs, views/partials/footer.ejs, views/partials/header.ejs, views/validationEmailSent.ejs
- Lien Accessibilité vers la section Accessibilité des mentions légales
- Ajout d'un texte explicatif des tests fait
- Corrections de html invalide
=> Link accessibility

controllers/createConfController.js, index.js, views/landing.ejs, views/partials/notificationError.ejs, views/partials/notificationInfo.ejs, views/partials/notificationSuccess.ejs
En attendant les composants notifications, on utilise des callouts pour que ça soit accessible en darkmode et lightmode.
=> Utilise des callout en attendant des notifications

controllers/createConfController.js, lib/db.js
Because it's an expected case.
=> When showing expired conf, don't log error

static/css/custom.css
=> Ajoute un bandeau sur toutes les pages

cron.js, lib/stats.js
=> Allége les logs du cron

static/css/custom.css, views/landing.ejs
Ajout d'un encart qui valorise les avantages de la plateforme :
=> Arguments de ventes sur la landing

controllers/sendValidationEmailController.js, views/partials/notificationError.ejs
=> Ajouter bouton de contact en cas d'erreur

controllers/createConfController.js, index.js, views/contact.ejs
=> Correction page de contact (suite à un merge trop rapide)

controllers/landingController.js, lib/db.js, lib/stats.js, migrations/20201106132737_add-free-phone-numbers-in-stats.js, static/js/charts.js, views/stats.ejs
Add stats of free phone numbers, using the last 1440 points.
When there is no value, the DB stores -1 as default, and the graph doesn't display the point.
=> Add free phone numbers stats

README.md, package-lock.json, package.json, views/contact.ejs, views/landing.ejs, views/legalNotice.ejs, views/partials/footer.ejs
Added a tool for checking HTML validity, and fixed current violations. 
(the mailto links were not encoded properly. I didn't do it very cleanly because we're going to get rid of them anyway)
=> Make HTML valid

cron.js
On pourrait même mettre moins, du genre 3 ou 5 mins ?
=> Pour alléger la charge, on passe les stats à toutes les 2 minutes

lib/emailer.js, views/confCreated.ejs
The scheme `tel:{phonenumber},,{pincode}` allows automatic dialing with the pin code.
Inspired by M$ Teams and tested on an iphone.
=> Add link with pincode to phone number to allows automatic dialing

views/validationEmailSent.ejs
J'ai pompé sur démarches simplifiés, on reçoit encore du support dessu.
=> Ajout indication 15 minutes pour l'antispam

.github/workflows/node.js.yml
=> ci: Lancement des tests par Github Actions

controllers/statusController.js, index.js, lib/db.js, test/statusControllerTest.js, urls.js
Add a status page : when you GET /status, it returns 200 if the DB and OVH are responding fine, otherwise 500.
(commit history is huge because I merged main into this branch, but don't worry the change is small)
=> feat: add status page

lib/conferences.js
J'ai fait le changement dans github ^^, on peut tester sur la review app
=> Supprime les rapports et enregistrements

lib/db.js, test/createConfControllerTest.js, test/sendValidationEmailControllerTest.js, test/utils.js
Je compte jusqu'a 3 et le CI passe. Un... deux...
=> fix: fix breaking tests

static/css/custom.css, views/legalNotice.ejs, views/partials/footer.ejs
The terms that we need to discuss have "(?)" next to them. 
We are still missing a "Gestion des cookies" link (not mentioned in terms of service)
=> feat: Add terms of service (CGU)

.github/workflows/node.js.yml, jobs/anonymizeConferences.js, jobs/sendSurveyEmails.js, lib/db.js, test/anonymizeConferenceTest.js, test/surveyEmailTest.js, test/utils.js
- light modification on code used by test, to return object instead of void and so, be more testable
- utility functions to insert bunch of data (in test/utils.js)
- 2 new test files
=> feat: add 2 tests for jobs

.env.sample, .gitignore, README.md, docker-compose.yml
Mise à jour readme + docker compose
=> doc: modify readme and docker compose file

README.md
Utile pour constituer le dossier d'appel d'offres.
=> Document OVH api calls

controllers/createConfController.js, lib/db.js, migrations/20210122164657_add-conference-day-in-conferences.js, test/createConfControllerTest.js, views/confCreated.ejs
https://github.com/betagouv/audioconf/issues/122
Ajouter `conferenceDay` dans la table `conferences` et l'utiliser pour afficher la date de la conférence.
=> Fix a timezone bug : conference day display is wrong

index.js, views/partials/footer.ejs, views/partials/header.ejs, views/stats.ejs
Fix for CodeQL warning : https://github.com/betagouv/audioconf/security/code-scanning/10?query=ref%3Arefs%2Fheads%2Fmain
=> Serve specific dist folders and not all node_modules

index.js, urls.js, views/contact.ejs, views/faq.ejs, views/partials/askToAddNewService.ejs, views/partials/footer.ejs, views/partials/header.ejs
Ajouter une page FAQ avec les questions les plus courantes reçues dans le support.
Ajout d'un lien "Une question ? " dans le header : 
Qui emmène vers la page FAQ : 
En bas de page, on renvoie l'utilisateur à la page Contact si la réponse n'a pas été trouvée.
=> Add faq page

index.js, static/css/custom.css, views/stats.ejs
J'enlève les graphiques fait-maison et je les ai ajoutés dans le metabase à la place.
=> Do not display home-made stats if metabase dashboard is present

index.js, package-lock.json, package.json, views/faq.ejs, views/partials/accordionBottom.ejs, views/partials/accordionTop.ejs, views/partials/header.ejs
Ajout d'une FAQ ( Feat : links to faq questions (#154) )
=> v1.13.0 - Ajout d'une FAQ

views/faq.ejs, views/partials/askToAddNewService.ejs
=> change information for 'Qui peut avoir un acces' in FAQ

lib/oidcAuth.js, test/magicLinkAuthTest.js
Fix https://github.com/betagouv/audioconf/issues/233
=> Clean up logs

lib/emailer.js, views/confCreated.ejs, views/emails/confWebAccess.ejs, views/faq.ejs, views/landing.ejs
Fixes https://github.com/betagouv/audioconf/issues/218
Avant -> Après
=> Expiration jusqu'au

lib/emailer.js
Votre réservation c'est terminé -> Votre réservation s'est terminée
=> Corrige des fautes de grammaire dans un e-mail
